Repository wecode-bootcamp-korea/28-2nd-BANGGUSEOK-Traveller-frontend, pull requests merged in 2022-01, with the labels that each got.

#2 [28기 안현재][Add] 공통컴포넌트 - 트립카드 구현
  src/components/TripCard/TripCard.js
  src/components/TripCard/TripCardStyles.js
  src/index.js
  src/styles/theme.js
Labels: Status: 리뷰 요청

#8 [28기 엄성용][Add] Nav bar 완료
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: Status: 리뷰 요청

#10 [28기 엄성용] Router 수정- Nav & footer 추가
  src/Router.js
  src/components/Nav/Nav.scss
Labels: Status: 리뷰 요청

#5 [28기 엄성용][Add] Modal 구현 중
  src/components/Modal/Modal.js
Labels: Status: 리뷰 요청

#4 [28기 엄성용][Add] RadiusButton styled components 수정 중
  src/components/Buttons/RadiusButton.js
Labels: Status: 리뷰 요청

#12 [28기 김정현][Modify] PaginationButtons 상호작용을 위한 수정 / 스타일 수정
  src/components/Buttons/PaginationButtons.js
  src/components/Buttons/PaginationButtonsStyle.js
Labels: Status: 리뷰 요청

#13 [28기 김정현] [Modify] 별점 서클 리팩토링
  src/components/RatingCircle/RatingCircle.js
Labels: Status: 리뷰 요청

#14 [28기 김정현][Add] Not Found 페이지 리팩토링
  src/components/NotFound/NotFound.js
Labels: Status: 리뷰 요청

#11 [28기 엄성용][ADD] Footer 구현
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: Status: 리뷰 요청

#6 [28기 안현재][Add] TripList페이지 리뷰 반영 완료
  public/data/tripListMockData.json
  src/components/Buttons/RadiusButton.js
  src/components/TripCard/TripCard.js
  src/components/TripCard/TripCardStyles.js
  src/pages/TripList/ListDisplay/ListDisplay.js
  src/pages/TripList/ListDisplay/ListDisplayStyles.js
  src/pages/TripList/ListDisplay/SingleList/SingleList.js
  src/pages/TripList/ListDisplay/SingleList/SingleListStyles.js
  src/pages/TripList/MainVisual/MainVisual.js
  src/pages/TripList/MainVisual/MainVisualStyles.js
  src/pages/TripList/TripList.js
  src/pages/TripList/TripListStyles.js
Labels: Status: 리뷰 요청

#16 [28기 안현재][Add] : TripDetail 페이지 공동작업 준비 완료
  src/pages/TripDetail/TripDetail.js
  src/pages/TripDetail/TripDetailBody/TripDetailBody.js
  src/pages/TripDetail/TripDetailHeader/TripDetailHeader.js
  src/pages/TripDetail/TripDetailHeader/TripDetailHeaderStyles.js
  src/pages/TripDetail/TripDetailVotes/TripDetailVotes.js
Labels: Status: 리뷰 요청

#15 [28기 엄성용][Add] Side hidden Bar 구현 중
  src/components/Buttons/RadiusButton.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/NavSidebar.js
  src/components/Nav/NavSidebar.scss
  src/pages/Main/Main.js
Labels: Status: 수정 요청

#17 [28기 엄성용] Footer & div 수정
  src/components/Modal/Modal.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: Status: 리뷰 요청

#21 [28기 김정현][Modify] 백엔드 키값 맞추기
  src/components/RatingCircle/RatingCircle.js
Labels: Status: 리뷰 요청

#18 [28기 김정현][Add] LoginModal 작업 진행.
  .env
  src/Router.js
  src/components/Footer/Footer.scss
  src/components/Kakao/KakaoLogin.js
  src/components/Kakao/KakaoRequest.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/NavSidebar.js
  src/components/Nav/hook/useNavToggles.js
  src/components/NavOutlet/WithNav.js
  src/components/NavOutlet/WithoutNav.js
Labels: Status: 리뷰 요청

#19 [28기 안현재] [Add] TripDetailBody 투표기능 제외한 UI 구현
  public/data/tripListMockData.json
  src/components/TripCard/TripCardStyles.js
  src/pages/TripDetail/TripDetail.js
  src/pages/TripDetail/TripDetailBody/TripDetailBody.js
  src/pages/TripDetail/TripDetailBody/TripDetailBodyDescription/TripDetailBodyDescription.js
  src/pages/TripDetail/TripDetailBody/TripDetailBodyDescription/TripDetailBodyStyles.js
  src/pages/TripDetail/TripDetailBody/TripDetailBodyStyles.js
  src/pages/TripDetail/TripDetailStyles.js
  src/pages/TripList/MainVisual/MainVisual.js
  src/pages/TripList/MainVisual/MainVisualStyles.js
Labels: Status: 리뷰 요청

#20 [28기 엄성용][Add] TripDetailVote 구현
  src/pages/TripDetail/TripDetailVotes/TripDetailVotes.js
Labels: Status: Rebase 요청

#23 [28기 김정현][Fix] Nav bar 상호작용 공사
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/NavSidebar.js
  src/components/Nav/NavSidebar.scss
  src/components/Nav/hook/useScrollbarToggle.js
Labels: Status: 리뷰 요청

#9 [28기 김정현][Add] Filter 페이지 로직 작성
  .env
  public/data/TripCards1.json
  src/Router.js
  src/components/Buttons/PaginationButtonsStyle.js
  src/pages/TripFilterLists/FilterBar.js
  src/pages/TripFilterLists/FilterListContainer.js
  src/pages/TripFilterLists/FilterTagsArea.js
  src/pages/TripFilterLists/FilterTripCards.js
  src/pages/TripFilterLists/FilterTripSkeletonCard.js
  src/pages/TripFilterLists/hook/useCreatePaginate.js
  src/pages/TripFilterLists/hook/useEditQuery.js
  src/pages/TripFilterLists/hook/useFetch.js
  src/pages/TripFilterLists/hook/useFilterToggle.js
  src/pages/TripFilterLists/hook/useGetLandscapes.js
Labels: Status: 리뷰 요청

#22 [28기 안현재] [FIX] TripDetailBody 리뷰반영 / 통신 후 데이터형 변경 / 투표기능추가구현
  public/data/tripListMockData.json
  src/components/TripCard/TripCard.js
  src/components/TripCard/TripCardStyles.js
  src/pages/TripDetail/TripDetail.js
  src/pages/TripDetail/TripDetailBody/TripDetailBody.js
  src/pages/TripDetail/TripDetailBody/TripDetailBodyDescription/TripDetailBodyDescription.js
  src/pages/TripDetail/TripDetailBody/TripDetailBodyDescription/TripDetailBodyDescriptionStyles.js
  src/pages/TripDetail/TripDetailBody/TripDetailBodyDescription/TripDetailBodyStyles.js
  src/pages/TripDetail/TripDetailBody/TripDetailBodyDescription/VoteCards/VoteCards.js
  src/pages/TripDetail/TripDetailBody/TripDetailBodyDescription/VoteCards/VoteCardsStyles.js
  src/pages/TripDetail/TripDetailBody/TripDetailBodyStyles.js
  src/pages/TripDetail/TripDetailHeader/TripDetailHeader.js
  src/pages/TripList/ListDisplay/ListDisplay.js
  src/pages/TripList/ListDisplay/SingleList/SingleList.js
  src/pages/TripList/TripList.js
Labels: Status: 리뷰 요청

#26 [28기 안현재] [Fix] TripDetailBody 백엔드 자료형 고려해 랜더링 수정 / 투표데이터 자료형 객체로 리팩토링
  package-lock.json
  public/data/tripListMockData.json
  src/pages/Main/ListDisplay/ListDisplay.js
  src/pages/Main/ListDisplay/ListDisplayStyles.js
  src/pages/Main/ListDisplay/SingleList/SingleList.js
  src/pages/Main/ListDisplay/SingleList/SingleListStyles.js
  src/pages/Main/Main.js
  src/pages/Main/MainStyles.js
  src/pages/Main/MainVisual/MainVisual.js
  src/pages/Main/MainVisual/MainVisualStyles.js
  src/pages/TripDetail/TripDetailBody/TripDetailBodyDescription/TripDetailBodyDescription.js
  src/pages/TripDetail/TripDetailBody/TripDetailBodyDescription/TripDetailBodyDescriptionStyles.js
  src/pages/TripList/TripList.js
Labels: Status: 리뷰 요청

#27 [28기 엄성용][Modify} Trip Detail Votes 수정 완료
  src/pages/TripDetail/TripDetailVotes/TripDetailVotes.js
Labels: Status: 리뷰 요청

#28 [28기 김정현][Fix] Main 합치기
  README.md
  src/Router.js
  src/atom/filters.js
  src/atom/users.js
  src/components/Buttons/PaginationButtons.js
  src/components/Kakao/KakaoRequest.js
  src/components/Modal/Modal.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/NavSidebar.js
  src/components/Nav/NavSidebar.scss
  src/pages/Main/Main.js
  src/pages/Main/MainStyles.js
  src/pages/TripDetail/TripDetail.js
  src/pages/TripDetail/TripDetailBody/TripDetailBodyDescription/TripDetailBodyDescription.js
  src/pages/TripDetail/TripDetailStyles.js
  src/pages/TripFilterLists/FilterBar.js
  src/pages/TripFilterLists/FilterListContainer.js
  src/pages/TripFilterLists/FilterListsRouteNesting.js
  src/pages/TripFilterLists/FilterTagsArea.js
  src/pages/TripFilterLists/FilterTripCards.js
  src/pages/TripFilterLists/hook/useCreatePaginate.js
  src/pages/TripFilterLists/hook/useEditQuery.js
  src/pages/TripFilterLists/hook/useFilterToggle.js
  src/pages/TripFilterLists/hook/useGetLandscapes.js
Labels: Status: 추가 기능 구현중
